In [3]:
import numpy as np

In [2]:
np.sum([1,3])

4

In [3]:
sum([1,3])


4

In [4]:
np.__version__


'1.11.3'

# Python Vs Numpy


Magic function always have % sign in frount of them

In [5]:
%time l1 = list(range(1,3000000))

Wall time: 105 ms


In [6]:
%time [x+5 for x in l1][:10]


Wall time: 583 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [7]:
%time l2 = np.arange(1,3000000)

Wall time: 10.9 ms


In [8]:

l1 = np.random.randn(2,2)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
#l1[row,col]

[[ 0.20003266  0.41968461]
 [-0.59051236  0.24993524]]
Dimension: 2
Shape: (2, 2)
Type: float64


In [10]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

l1[1,2,1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension: 3
Shape: (3, 3, 3)
Type: int32


16

In [11]:
#l1[i,j,k]
#  i=numbers of pages, j=numbers of rows,k=numbers of colums

In [13]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)

l1 = l1 + 5
l1

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28],
        [29, 30, 31]]])

# A Multidimensional Array Object

In [5]:
l1 = np.arange(1,13).reshape((3,4))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension: 2
Shape: (3, 4)
Type: int32


# Creating ndarrays

In [4]:
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
type(a)

<class 'list'>
False


numpy.ndarray


# np.asarray

In [5]:
# 1 array->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #2
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#3

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray