In [2]:
import numpy as np

In [2]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(a.dtype)

int32


In [6]:
a = np.arange(1,13).reshape(3,4).astype('float64')
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [7]:
a = np.arange(1,13).astype(np.float64).reshape(3,4)
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [8]:
a = np.arange(1,13, dtype=np.float32).reshape(3,4)
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]], dtype=float32)

In [9]:
np.random.randn(3,3,3) * 5

array([[[ 5.12852032,  5.34775241, -9.1500733 ],
        [-7.71823772, -2.61624674, -0.34211554],
        [ 4.96109847, -5.59781136,  0.84977835]],

       [[-0.20869605,  0.55189495,  0.75209811],
        [ 3.2886238 ,  3.63773634,  3.82352006],
        [-7.22973585, -4.84902353, -5.29724091]],

       [[ 1.08609814, -2.52127939,  5.82108867],
        [-4.31764639, -2.91247848, -1.86496258],
        [-2.09797998, -7.21156563, -2.0914682 ]]])

In [10]:
a = np.ones((3,3,3), dtype=np.int64)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int64)

In [11]:
a = np.zeros((3,3,3))
a

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [12]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [13]:
a.shape

(3, 3, 3)

In [14]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [15]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.ones_like(a) * 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [18]:
np.ones_like(a) + 4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
np.full((3,3,3), 5) #here it will create the 3 slides, each silide will have 3 rows and 3 cloums

C:\Users\Hp\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((3, 3, 3), 5) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[[ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.]],

       [[ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.]],

       [[ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.]]])

In [21]:
np.full_like(a, 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [27]:
np.empty((3,3,3))#loads the garbege value rendomly

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [23]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [25]:
np.identity(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [26]:
np.identity??


# Data Types for ndarrays

In [3]:
a = np.arange(1,13, dtype='int')
print(a.dtype)

int32


In [4]:

a = np.arange(1,13, dtype=np.int64)
print(a.dtype)

int64


In [5]:
a = np.arange(1,13, dtype='i8')
print(a.dtype)


int64


In [6]:
a = a.astype(np.float64)
print(a.dtype)

float64


In [7]:
a = np.arange(1,28, dtype='g').reshape((3,3,3))
print(a)
print(a.dtype)

[[[ 1.0  2.0  3.0]
  [ 4.0  5.0  6.0]
  [ 7.0  8.0  9.0]]

 [[ 10.0  11.0  12.0]
  [ 13.0  14.0  15.0]
  [ 16.0  17.0  18.0]]

 [[ 19.0  20.0  21.0]
  [ 22.0  23.0  24.0]
  [ 25.0  26.0  27.0]]]
float64


In [8]:
np.full_like(a, 5, dtype=a.dtype)

array([[[ 5.0,  5.0,  5.0],
        [ 5.0,  5.0,  5.0],
        [ 5.0,  5.0,  5.0]],

       [[ 5.0,  5.0,  5.0],
        [ 5.0,  5.0,  5.0],
        [ 5.0,  5.0,  5.0]],

       [[ 5.0,  5.0,  5.0],
        [ 5.0,  5.0,  5.0],
        [ 5.0,  5.0,  5.0]]], dtype=float64)

In [9]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [10]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]], dtype=bool)

In [11]:
a[(a%3==0) | (a%5==0)]

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27])

In [12]:
a[(a%3==0) & (a%5==0)]

array([15])

In [13]:
a[~(a%3==0)]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [14]:
a[(~a%3==0)]

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [15]:
a = np.array([1,3,5,6,8])
b = np.array([True, False, True,False,False])
a[~b]

array([3, 6, 8])

In [16]:
a = np.array([1,3,5,6,8])
b = [True, False, True,False,False]
a[~b]

TypeError: bad operand type for unary ~: 'list'