In [16]:
import numpy as np

In [17]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)
print(names, data, sep="\n")

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 0.82201639 -0.72360043 -1.18250765  1.43157659]
 [ 0.35285198  1.09937322  0.60842454  1.18903426]
 [-1.29280346 -1.13945678  0.4418352   0.82556802]
 [-1.22904083 -0.96979559 -0.82857635  0.13389185]
 [ 0.06449827  0.3634683   0.14695827 -0.96236509]
 [-0.31985443  1.24240737 -1.05427595 -0.5311961 ]]


In [18]:
names=="Qasim"

array([ True, False, False, False,  True, False], dtype=bool)

In [22]:
data[[ True, False, False, False,  True, False]]

C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  if __name__ == '__main__':


array([[-0.21770062,  0.29035891, -0.1785776 , -1.32086681],
       [-0.79682092, -1.32823375, -1.06956493, -0.71381625],
       [-0.79682092, -1.32823375, -1.06956493, -0.71381625],
       [-0.79682092, -1.32823375, -1.06956493, -0.71381625],
       [-0.21770062,  0.29035891, -0.1785776 , -1.32086681],
       [-0.79682092, -1.32823375, -1.06956493, -0.71381625]])

In [20]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)
print(names, data, sep="\n")

data[names=="Qasim"]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 1.06581857  1.00250694 -0.34624189 -1.33652734]
 [-1.49478347  0.16046944  0.80079412  0.06264471]
 [ 0.26896921 -1.84873317 -0.25205839 -1.22614199]
 [-0.70098737  0.51717896 -0.74081395 -0.66168396]
 [ 0.1690872   1.36117137 -0.36840717 -0.88497694]
 [-0.48050021  0.10877613 -0.15261811 -1.23843433]]


array([[ 1.06581857,  1.00250694, -0.34624189, -1.33652734],
       [ 0.1690872 ,  1.36117137, -0.36840717, -0.88497694]])

In [21]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)

print(names, data, sep="\n")

data[names=="Qasim"][:,[-1,0,2]]


['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[-0.79682092 -1.32823375 -1.06956493 -0.71381625]
 [-0.21770062  0.29035891 -0.1785776  -1.32086681]
 [ 0.87753966 -1.13181471 -0.35867534  1.17018316]
 [-1.61032669  0.27801156 -2.16823007  0.28203677]
 [-0.27246109  0.2246998   0.15138956  1.33325424]
 [-0.84666964  0.95381078 -0.39527257 -0.70586407]]


array([[-0.71381625, -0.79682092, -1.06956493],
       [ 1.33325424, -0.27246109,  0.15138956]])

In [23]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)

print(names, data, sep="\n")

#data[~(names == "Qasim") | ~(names=="Ali")]
data[(names != "Qasim") | (names!="Ali")]
data[:,::-1]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[-0.11693583  0.78127541 -0.30354395  1.25237996]
 [-0.51639339  0.81341229  1.14658775 -0.16467285]
 [-1.25783893  0.59095433 -0.1563029   0.54335258]
 [-0.85828817  1.19171327 -1.2327269  -0.37018852]
 [-1.86619252  1.06248397 -0.22191449  1.89008666]
 [-0.87800408  1.18041013 -0.4499678  -0.71815177]]


array([[ 1.25237996, -0.30354395,  0.78127541, -0.11693583],
       [-0.16467285,  1.14658775,  0.81341229, -0.51639339],
       [ 0.54335258, -0.1563029 ,  0.59095433, -1.25783893],
       [-0.37018852, -1.2327269 ,  1.19171327, -0.85828817],
       [ 1.89008666, -0.22191449,  1.06248397, -1.86619252],
       [-0.71815177, -0.4499678 ,  1.18041013, -0.87800408]])


# Fancy

In [2]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [3]:
#arr[slide, row, col]

In [4]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()
print(a[[-1,-2,0],:,:])#: its means that all the row if placed at row place
print(a[[-1,-2,0]])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [6]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()
#print(a[:,[1,2], :]) #[all slids , row one and two , all colums]  
print(a[:,1:, :]) #[all slids , all rows after 1 , all colums]  

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[ 3  4  5]
  [ 6  7  8]]

 [[12 13 14]
  [15 16 17]]

 [[21 22 23]
  [24 25 26]]]


In [7]:
l = [1,29,8,2,9,3,2,1]
l[:3]
l[:3] = 5

TypeError: can only assign an iterable

In [8]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
a[1] = 5
a

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 5,  5,  5],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
a = np.arange(3*3).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#a[1:,1:]
a[1:3,1:3]
#a[-2:,-2:]

array([[4, 5],
       [7, 8]])

In [11]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i in range(len(a)):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [24]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i in range(a.shape[0]):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [25]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [26]:
list(enumerate([8,9,10]))

[(0, 8), (1, 9), (2, 10)]

In [27]:
print(a)
a[[5,4,3]]


[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


array([[5, 5, 5, 5],
       [4, 4, 4, 4],
       [3, 3, 3, 3]])

In [28]:
a = np.arange(8*4).reshape((8,4))
print(a)
a[[5,4,3]][:,[3,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[23, 21],
       [19, 17],
       [15, 13]])

In [29]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

# Transposing Arrays and Swapping Axes


In [30]:
a = np.arange(4*3).reshape((4,3))
print(a)
print(a.T)
print(a.transpose())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [31]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a * b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[ 3  8]
 [15 24]]


In [32]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a @ b) #linear algabra dot product

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [33]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a.dot(b))

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [40]:
a
print(a)
a.T

[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

In [35]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [41]:
a @ a.T #array([[1, 2],  @  array([[1, 3],
            # [3, 4]])          [2, 4]])

array([[ 5, 11],
       [11, 25]])

In [42]:
a = np.arange(27).reshape((3,3,3))
print(a)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [43]:
a.T


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [44]:
print(a)
print(a.transpose((2,1,0)))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [45]:
a = np.arange(12).reshape(4,3)
print(a)
print(a.swapaxes(1,0))
#print(a.reshape((a.shape[1], a.shape[0])))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [46]:
a.ndim

2

In [47]:
a.shape

(4, 3)

# Universal Functions: Fast Element-Wise Array Functions

In [49]:
l = np.array([-1,3,-5,8,0])
np.abs(l)

array([1, 3, 5, 8, 0])

In [50]:
l = np.array([-1,3,-5,8,0])
np.fabs(l)

array([ 1.,  3.,  5.,  8.,  0.])

In [51]:
np.sqrt([36,25,9])

array([ 6.,  5.,  3.])

In [52]:
np.square([2,3,4])

array([ 4,  9, 16], dtype=int32)

In [53]:
np.exp([2,3,5])

array([   7.3890561 ,   20.08553692,  148.4131591 ])

In [54]:
np.ceil([2.2, 3.1, 2.6])

array([ 3.,  4.,  3.])

In [55]:
np.floor([2.2, 3.1, 2.6])

array([ 2.,  3.,  2.])

In [56]:
a = np.array([2.2, 3.1, 2.6])
print(a)
print()
f, w = np.modf(a)
print(w,f, sep="\n\n")

[ 2.2  3.1  2.6]

[ 2.  3.  2.]

[ 0.2  0.1  0.6]


In [57]:
for i in [2.2, 3.1, 2.6]:
    i= str(i).split(".")
    print(i[0], i[1])

2 2
3 1
2 6


In [58]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.maximum(a,b))

[ 2  4 45]


In [59]:
a = np.array([1,3,45])
b = np.array([2,4,3])

np.fmax(a,b)

array([ 2,  4, 45])

In [60]:
a = np.arange(6*2).reshape((6,2))
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

# Expressing Conditional Logic as Array Operations

In [61]:
a = np.arange(3*3*3).reshape((3,3,3))
a %3 == 0

array([[[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]]], dtype=bool)

np.where(condition, value_True, value_false)



In [62]:
np.where(a%3==0, "Yes","No")

array([[['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']]], 
      dtype='<U3')

In [63]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.where(a>b, a, b))


[ 2  4 45]
